services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - ENV FLASK_APP=app
      - ENV FLASK_ENV=development
      - JWT_SECRET_KEY=my-secret-key
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d task_mng"]
      interval: 10s
      timeout: 10s
      retries: 10
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/redis
volumes:
  postgres_data:
  redis_data:
